version: '3.8'

services:
  web:
    build: ./src           
    container_name: building-app-web
    ports:
      - "8080:80"          
    environment:
      - DB_HOST=db         
      - DB_USER=root       
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=login_api_demo
    depends_on:
      - db                 
    networks:
      - project-network

  db:
    image: mysql:latest    
    container_name: building-app-db
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=login_api_demo                  
    volumes:
      - db-data:/var/lib/mysql 
    networks:
      - project-network

networks:
  project-network:         

volumes:
  db-data:                 
